In [13]:
import pandas as pd 
path= 'C://Users/bozdoga/Documents/Data Filtering/dummydata.xlsx'
folder_path= 'C://Users/bozdoga/Documents/Data Filtering/output/'

In [4]:
data = pd.read_excel(path)
data.describe()

,asin,classification_date,reviewer_reason,active_marketplaces,node_id
count,9999,9999,9999,9999,9999
unique,9965,1821,1122,365,7
top,B08Z43HZXP,2019-12-16 00:00:00,DPI,"DE,ES,FR,IT,NL,PL,SE,UK",PNQ
freq,4,15,4640,2963,8110
first,NaN,2018-01-01 00:00:00,NaN,NaN,NaN
last,NaN,2023-01-01 00:00:00,NaN,NaN,NaN

In [6]:
data_onlyde  = data[(data.active_marketplaces)=='DE']
data_allde = data[(data.active_marketplaces.str.contains('DE'))]
data_de = pd.concat([data_allde,data_onlyde]).drop_duplicates(keep=False)


data_de.head(200)

,asin,classification_date,reviewer_reason,active_marketplaces,node_id
0,B088FW3H7F,2020-03-20,PTG,"DE,ES,FR,IT,UK",PNQ
1,B01E7PV73C,2020-07-02,DPI,"DE,ES,FR,IT,NL,PL,SE,TR,UK,US",PNQ
2,B01C8HIA22,2022-05-02,DPI,"DE,ES,FR,IT,NL,SE,UK",PNQ
3,B08KY8B6ZX,2020-08-15,DPI,"DE,ES,FR,IT,UK",PNQ
5,B074XFYTK3,2019-12-20,"Inflow Queue_ML output_04Jan2021,ML","DE,ES,FR,IT,NL,PL,SE,TR,UK",PNQ
...,...,...,...,...,...
231,B08N9TCT7X,2019-02-22,DPI,"DE,ES,FR,IT,PL,UK",PNQ
232,B08L7C1R13,2018-07-09,DPI,"DE,ES,FR,IT,NL,PL,SE,UK",PNQ
233,B08KZRNVJ3,2019-02-23,DPI,"DE,ES,FR,IT,NL,PL,SE,UK",PNQ
234,B08P3RLJF1,2020-02-02,DPI,"DE,ES,FR,IT,NL,SE,UK",PNQ
235,B08RP7W9RJ,2018-04-01,DPI,"DE,ES,FR,IT,NL,PL,SE,UK,US",PNQ

In [7]:
data_onlyse  = data[(data.active_marketplaces)=='SE']
data_allse = data[(data.active_marketplaces.str.contains('SE'))]
data_se = pd.concat([data_allse,data_onlyde]).drop_duplicates(keep=False)

data_onlydtr  = data[(data.active_marketplaces)=='TR']
data_alltr = data[(data.active_marketplaces.str.contains('TR'))]
data_tr = pd.concat([data_alltr,data_onlyde]).drop_duplicates(keep=False)

data_onlydpl  = data[(data.active_marketplaces)=='PL']
data_allpl = data[(data.active_marketplaces.str.contains('PL'))]
data_pl = pd.concat([data_allpl,data_onlyde]).drop_duplicates(keep=False)

In [8]:
data_se.head(100)

,asin,classification_date,reviewer_reason,active_marketplaces,node_id
1,B01E7PV73C,2020-07-02,DPI,"DE,ES,FR,IT,NL,PL,SE,TR,UK,US",PNQ
2,B01C8HIA22,2022-05-02,DPI,"DE,ES,FR,IT,NL,SE,UK",PNQ
5,B074XFYTK3,2019-12-20,"Inflow Queue_ML output_04Jan2021,ML","DE,ES,FR,IT,NL,PL,SE,TR,UK",PNQ
8,B07X1S1YZ4,2022-05-29,DPI,"DE,ES,FR,IT,NL,SE,UK",PNQ
9,B089D14DS3,2019-02-27,DPI,"DE,ES,FR,IT,JP,NL,PL,SE,UK,US",PNQ
...,...,...,...,...,...
230,B07KN2FRGM,2019-02-01,DPI,"DE,ES,FR,IT,NL,PL,SE,UK",PNQ
232,B08L7C1R13,2018-07-09,DPI,"DE,ES,FR,IT,NL,PL,SE,UK",PNQ
233,B08KZRNVJ3,2019-02-23,DPI,"DE,ES,FR,IT,NL,PL,SE,UK",PNQ
234,B08P3RLJF1,2020-02-02,DPI,"DE,ES,FR,IT,NL,SE,UK",PNQ
235,B08RP7W9RJ,2018-04-01,DPI,"DE,ES,FR,IT,NL,PL,SE,UK,US",PNQ

In [14]:
with pd.ExcelWriter(folder_path +'DE Training Data.xlsx') as writer:
    data_onlyde.to_excel(writer,sheet_name='Only DE ASINs')
    data_de.to_excel(writer,sheet_name='DE ASINs')

In [12]:
with pd.ExcelWriter(folder_path +'SE Training Data.xlsx') as writer:
    data_onlyse.to_excel(writer,sheet_name='Only SE ASINs')
    data_se.to_excel(writer,sheet_name='SE ASINs')

with pd.ExcelWriter(folder_path +'TR Training Data.xlsx') as writer:
    data_onlydtr.to_excel(writer,sheet_name='Only TR ASINs')
    data_tr.to_excel(writer,sheet_name='TR ASINs')

with pd.ExcelWriter(folder_path +'PL Training Data.xlsx') as writer:
    data_onlydpl.to_excel(writer,sheet_name='Only PL ASINs')
    data_pl.to_excel(writer,sheet_name='PL ASINs')